-- Initial schema migration generated from DER model.
-- Source model: schema_final.sql (MySQL Workbench export)

BEGIN;

CREATE SCHEMA IF NOT EXISTS final;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_type') THEN
    CREATE TYPE final.gender_type AS ENUM ('M', 'F', 'Other');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_type_type') THEN
    CREATE TYPE final.attendance_type_type AS ENUM ('individual', 'general');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status_type') THEN
    CREATE TYPE final.attendance_status_type AS ENUM ('attended', 'absent');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'group_role_type') THEN
    CREATE TYPE final.group_role_type AS ENUM ('member', 'leader', 'assistant');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS final.member_status (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS final.family (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS final.member (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  middle_name VARCHAR(45),
  last_name_parental VARCHAR(45) NOT NULL,
  last_name_maternal VARCHAR(45),
  address VARCHAR(45),
  birth_date DATE,
  gender final.gender_type NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(100) UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  marital_status VARCHAR(45),
  family_role VARCHAR(45),
  is_baptized BOOLEAN,
  baptized_location VARCHAR(45),
  member_status_id INTEGER NOT NULL,
  family_id INTEGER NOT NULL,
  CONSTRAINT fk_member_member_status
    FOREIGN KEY (member_status_id) REFERENCES final.member_status (id),
  CONSTRAINT fk_member_family1
    FOREIGN KEY (family_id) REFERENCES final.family (id)
);

CREATE INDEX IF NOT EXISTS fk_member_member_status_idx ON final.member (member_status_id);
CREATE INDEX IF NOT EXISTS fk_member_family1_idx ON final.member (family_id);

CREATE TABLE IF NOT EXISTS final.event_series (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(45) NOT NULL,
  description TEXT,
  attendance_type final.attendance_type_type NOT NULL,
  is_recurring BOOLEAN NOT NULL,
  recurrence_rule TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS final.event_instance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_datetime TIMESTAMP NOT NULL,
  end_datetime TIMESTAMP NOT NULL,
  event_series_id INTEGER NOT NULL,
  attendee_count INTEGER,
  CONSTRAINT fk_event_instance_event_series1
    FOREIGN KEY (event_series_id) REFERENCES final.event_series (id)
);

CREATE INDEX IF NOT EXISTS fk_event_instance_event_series1_idx ON final.event_instance (event_series_id);

CREATE TABLE IF NOT EXISTS final.event_attendance (
  member_id INTEGER NOT NULL,
  event_instance_id INTEGER NOT NULL,
  status final.attendance_status_type NOT NULL,
  PRIMARY KEY (member_id, event_instance_id),
  CONSTRAINT fk_member_has_event_instance_member1
    FOREIGN KEY (member_id) REFERENCES final.member (id),
  CONSTRAINT fk_member_has_event_instance_event_instance1
    FOREIGN KEY (event_instance_id) REFERENCES final.event_instance (id)
);

CREATE INDEX IF NOT EXISTS fk_member_has_event_instance_event_instance1_idx
  ON final.event_attendance (event_instance_id);
CREATE INDEX IF NOT EXISTS fk_member_has_event_instance_member1_idx
  ON final.event_attendance (member_id);

CREATE TABLE IF NOT EXISTS final.event_tag (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL UNIQUE,
  color VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS final.event_series_tag_map (
  event_tag_id INTEGER NOT NULL,
  event_series_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (event_tag_id, event_series_id),
  CONSTRAINT fk_event_tag_has_event_series_event_tag1
    FOREIGN KEY (event_tag_id) REFERENCES final.event_tag (id),
  CONSTRAINT fk_event_tag_has_event_series_event_series1
    FOREIGN KEY (event_series_id) REFERENCES final.event_series (id)
);

CREATE INDEX IF NOT EXISTS fk_event_tag_has_event_series_event_series1_idx
  ON final.event_series_tag_map (event_series_id);
CREATE INDEX IF NOT EXISTS fk_event_tag_has_event_series_event_tag1_idx
  ON final.event_series_tag_map (event_tag_id);

CREATE TABLE IF NOT EXISTS final.small_group (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(45),
  meeting_day VARCHAR(45) NOT NULL,
  meeting_time TIME NOT NULL,
  location VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS final.group_membership (
  small_group_id INTEGER NOT NULL,
  member_id INTEGER NOT NULL,
  joined_at DATE NOT NULL,
  left_at DATE,
  role final.group_role_type NOT NULL,
  PRIMARY KEY (small_group_id, member_id, joined_at),
  CONSTRAINT fk_small_group_has_member_small_group1
    FOREIGN KEY (small_group_id) REFERENCES final.small_group (id),
  CONSTRAINT fk_small_group_has_member_member1
    FOREIGN KEY (member_id) REFERENCES final.member (id)
);

CREATE INDEX IF NOT EXISTS fk_small_group_has_member_member1_idx
  ON final.group_membership (member_id);
CREATE INDEX IF NOT EXISTS fk_small_group_has_member_small_group1_idx
  ON final.group_membership (small_group_id);

CREATE TABLE IF NOT EXISTS final.small_group_tag (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL UNIQUE,
  color VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS final.small_group_tag_map (
  group_tag_id INTEGER NOT NULL,
  small_group_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (group_tag_id, small_group_id),
  CONSTRAINT fk_group_tag_has_small_group_group_tag1
    FOREIGN KEY (group_tag_id) REFERENCES final.small_group_tag (id),
  CONSTRAINT fk_group_tag_has_small_group_small_group1
    FOREIGN KEY (small_group_id) REFERENCES final.small_group (id)
);

CREATE INDEX IF NOT EXISTS fk_group_tag_has_small_group_small_group1_idx
  ON final.small_group_tag_map (small_group_id);
CREATE INDEX IF NOT EXISTS fk_group_tag_has_small_group_group_tag1_idx
  ON final.small_group_tag_map (group_tag_id);

CREATE TABLE IF NOT EXISTS final.attendance_group (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS final.event_instance_group_count (
  attendance_group_id INTEGER NOT NULL,
  event_instance_id INTEGER NOT NULL,
  count INTEGER NOT NULL,
  PRIMARY KEY (attendance_group_id, event_instance_id),
  CONSTRAINT fk_event_series_has_grupuos_grupuos1
    FOREIGN KEY (attendance_group_id) REFERENCES final.attendance_group (id),
  CONSTRAINT fk_event_series_has_grupuos_event_instance1
    FOREIGN KEY (event_instance_id) REFERENCES final.event_instance (id)
);

CREATE INDEX IF NOT EXISTS fk_event_series_has_grupuos_grupuos1_idx
  ON final.event_instance_group_count (attendance_group_id);
CREATE INDEX IF NOT EXISTS fk_event_series_has_grupuos_event_instance1_idx
  ON final.event_instance_group_count (event_instance_id);

CREATE TABLE IF NOT EXISTS final.user_account (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(45) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  last_login TIMESTAMP
);

COMMIT;
