"""Initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-04-24
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_attendance_type_enum') THEN
            CREATE TYPE event_attendance_type_enum AS ENUM ('general', 'individual');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'member_attendance_status_enum') THEN
            CREATE TYPE member_attendance_status_enum AS ENUM ('pending', 'attended', 'absent', 'late', 'excused', 'unknown');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'member_registration_status_enum') THEN
            CREATE TYPE member_registration_status_enum AS ENUM ('registered', 'cancelled', 'waitlisted', 'unknown');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'day_of_week_enum') THEN
            CREATE TYPE day_of_week_enum AS ENUM ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'group_membership_status_enum') THEN
            CREATE TYPE group_membership_status_enum AS ENUM ('leader', 'member', 'unknown');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_enum') THEN
            CREATE TYPE gender_enum AS ENUM ('M', 'F', 'Other');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'marital_status_enum') THEN
            CREATE TYPE marital_status_enum AS ENUM ('Single', 'Married', 'Divorced', 'Widowed');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recurrence_type_enum') THEN
            CREATE TYPE recurrence_type_enum AS ENUM ('daily', 'weekly', 'monthly', 'yearly', 'none');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_series_status_enum') THEN
            CREATE TYPE event_series_status_enum AS ENUM ('draft', 'active', 'paused', 'cancelled', 'completed');
          END IF;

          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'small_group_status_enum') THEN
            CREATE TYPE small_group_status_enum AS ENUM ('active', 'paused');
          END IF;
        END
        $$;

        CREATE TABLE IF NOT EXISTS member_status (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL UNIQUE
        );

        CREATE TABLE IF NOT EXISTS family (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL
        );

        CREATE TABLE IF NOT EXISTS member (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL,
          middle_name VARCHAR(45),
          last_name_parental VARCHAR(45) NOT NULL,
          last_name_maternal VARCHAR(45),
          address VARCHAR(45),
          birth_date DATE,
          gender gender_enum NOT NULL,
          phone VARCHAR(20),
          email VARCHAR(100) UNIQUE,
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP,
          marital_status marital_status_enum,
          family_role VARCHAR(45),
          is_baptized BOOLEAN,
          baptized_location VARCHAR(45),
          member_status_id INTEGER NOT NULL,
          family_id INTEGER NOT NULL,
          CONSTRAINT fk_member_member_status
            FOREIGN KEY (member_status_id) REFERENCES member_status (id),
          CONSTRAINT fk_member_family1
            FOREIGN KEY (family_id) REFERENCES family (id)
        );

        CREATE INDEX IF NOT EXISTS fk_member_member_status_idx ON member (member_status_id);
        CREATE INDEX IF NOT EXISTS fk_member_family1_idx ON member (family_id);

        CREATE TABLE IF NOT EXISTS event_series (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL UNIQUE,
          description VARCHAR(255),
          attendance_type event_attendance_type_enum NOT NULL,
          recurrence_type recurrence_type_enum NOT NULL DEFAULT 'none',
          recurrence_rule VARCHAR(255),
          status event_series_status_enum NOT NULL DEFAULT 'active',
          location VARCHAR(255),
          start_time TIME,
          end_time TIME,
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS event_instance (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          location VARCHAR(255),
          attendance_notes VARCHAR(500),
          start_datetime TIMESTAMP NOT NULL,
          end_datetime TIMESTAMP NOT NULL,
          attendee_count INTEGER NOT NULL DEFAULT 0,
          event_series_id INTEGER NOT NULL,
          CONSTRAINT fk_event_instance_event_series1
            FOREIGN KEY (event_series_id) REFERENCES event_series (id)
        );

        CREATE INDEX IF NOT EXISTS fk_event_instance_event_series1_idx ON event_instance (event_series_id);

        CREATE TABLE IF NOT EXISTS event_member_attendance (
          event_instance_id INTEGER NOT NULL,
          member_id INTEGER NOT NULL,
          registration_status member_registration_status_enum NOT NULL DEFAULT 'registered',
          attendance_status member_attendance_status_enum NOT NULL DEFAULT 'pending',
          PRIMARY KEY (event_instance_id, member_id),
          CONSTRAINT fk_member_has_event_instance_member1
            FOREIGN KEY (member_id) REFERENCES member (id),
          CONSTRAINT fk_member_has_event_instance_event_instance1
            FOREIGN KEY (event_instance_id) REFERENCES event_instance (id)
        );

        CREATE INDEX IF NOT EXISTS fk_member_has_event_instance_event_instance1_idx
          ON event_member_attendance (event_instance_id);
        CREATE INDEX IF NOT EXISTS fk_member_has_event_instance_member1_idx
          ON event_member_attendance (member_id);

        CREATE TABLE IF NOT EXISTS event_tag (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL UNIQUE,
          color VARCHAR(7)
        );

        CREATE TABLE IF NOT EXISTS event_series_tag_map (
          event_series_id INTEGER NOT NULL,
          event_tag_id INTEGER NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP,
          PRIMARY KEY (event_series_id, event_tag_id),
          CONSTRAINT fk_event_tag_has_event_series_event_tag1
            FOREIGN KEY (event_tag_id) REFERENCES event_tag (id),
          CONSTRAINT fk_event_tag_has_event_series_event_series1
            FOREIGN KEY (event_series_id) REFERENCES event_series (id)
        );

        CREATE INDEX IF NOT EXISTS fk_event_tag_has_event_series_event_series1_idx
          ON event_series_tag_map (event_series_id);
        CREATE INDEX IF NOT EXISTS fk_event_tag_has_event_series_event_tag1_idx
          ON event_series_tag_map (event_tag_id);

        CREATE TABLE IF NOT EXISTS small_group (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL UNIQUE,
          description VARCHAR(255),
          meeting_day day_of_week_enum NOT NULL,
          meeting_time TIME NOT NULL,
          location VARCHAR(255),
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP,
          status small_group_status_enum NOT NULL DEFAULT 'active'
        );

        CREATE TABLE IF NOT EXISTS group_membership (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          member_id INTEGER NOT NULL,
          small_group_id INTEGER NOT NULL,
          role group_membership_status_enum NOT NULL DEFAULT 'unknown',
          joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          left_at TIMESTAMP,
          CONSTRAINT fk_small_group_has_member_small_group1
            FOREIGN KEY (small_group_id) REFERENCES small_group (id),
          CONSTRAINT fk_small_group_has_member_member1
            FOREIGN KEY (member_id) REFERENCES member (id)
        );

        CREATE INDEX IF NOT EXISTS fk_small_group_has_member_member1_idx
          ON group_membership (member_id);
        CREATE INDEX IF NOT EXISTS fk_small_group_has_member_small_group1_idx
          ON group_membership (small_group_id);

        CREATE TABLE IF NOT EXISTS small_group_tag (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL UNIQUE,
          color VARCHAR(7)
        );

        CREATE TABLE IF NOT EXISTS small_group_tag_map (
          small_group_id INTEGER NOT NULL,
          tag_id INTEGER NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP,
          PRIMARY KEY (small_group_id, tag_id),
          CONSTRAINT fk_group_tag_has_small_group_group_tag1
            FOREIGN KEY (tag_id) REFERENCES small_group_tag (id),
          CONSTRAINT fk_group_tag_has_small_group_small_group1
            FOREIGN KEY (small_group_id) REFERENCES small_group (id)
        );

        CREATE INDEX IF NOT EXISTS fk_group_tag_has_small_group_small_group1_idx
          ON small_group_tag_map (small_group_id);
        CREATE INDEX IF NOT EXISTS fk_group_tag_has_small_group_group_tag1_idx
          ON small_group_tag_map (tag_id);

        CREATE TABLE IF NOT EXISTS attendance_group (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(45) NOT NULL UNIQUE,
          description VARCHAR(255)
        );

        CREATE TABLE IF NOT EXISTS event_instance_group_count (
          event_instance_id INTEGER NOT NULL,
          attendance_group_id INTEGER NOT NULL,
          count INTEGER NOT NULL,
          PRIMARY KEY (event_instance_id, attendance_group_id),
          CONSTRAINT fk_event_series_has_grupuos_grupuos1
            FOREIGN KEY (attendance_group_id) REFERENCES attendance_group (id),
          CONSTRAINT fk_event_series_has_grupuos_event_instance1
            FOREIGN KEY (event_instance_id) REFERENCES event_instance (id)
        );

        CREATE INDEX IF NOT EXISTS fk_event_series_has_grupuos_grupuos1_idx
          ON event_instance_group_count (attendance_group_id);
        CREATE INDEX IF NOT EXISTS fk_event_series_has_grupuos_event_instance1_idx
          ON event_instance_group_count (event_instance_id);

        CREATE TABLE IF NOT EXISTS user_account (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username VARCHAR(45) NOT NULL UNIQUE,
          password_hash VARCHAR(255) NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          last_login TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS user_logs (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL,
          action_type VARCHAR(45) NOT NULL,
          description VARCHAR(255),
          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT fk_user_logs_user_account1
            FOREIGN KEY (user_id) REFERENCES user_account (id)
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS user_logs;
        DROP TABLE IF EXISTS user_account;
        DROP TABLE IF EXISTS event_instance_group_count;
        DROP TABLE IF EXISTS attendance_group;
        DROP TABLE IF EXISTS small_group_tag_map;
        DROP TABLE IF EXISTS small_group_tag;
        DROP TABLE IF EXISTS group_membership;
        DROP TABLE IF EXISTS small_group;
        DROP TABLE IF EXISTS event_series_tag_map;
        DROP TABLE IF EXISTS event_tag;
        DROP TABLE IF EXISTS event_member_attendance;
        DROP TABLE IF EXISTS event_instance;
        DROP TABLE IF EXISTS event_series;
        DROP TABLE IF EXISTS member;
        DROP TABLE IF EXISTS family;
        DROP TABLE IF EXISTS member_status;

        DROP TYPE IF EXISTS event_series_status_enum;
        DROP TYPE IF EXISTS recurrence_type_enum;
        DROP TYPE IF EXISTS marital_status_enum;
        DROP TYPE IF EXISTS gender_enum;
        DROP TYPE IF EXISTS group_membership_status_enum;
        DROP TYPE IF EXISTS day_of_week_enum;
        DROP TYPE IF EXISTS member_attendance_status_enum;
        DROP TYPE IF EXISTS member_registration_status_enum;
        DROP TYPE IF EXISTS small_group_status_enum;
        DROP TYPE IF EXISTS event_attendance_type_enum;
        """
    )
